import { InventoryItem } from "./types";

export const MOCK_ITEMS: InventoryItem[] = [
  {
    id: "1",
    name: "Organic Whole Milk",
    category: "Dairy",
    unit_type: "gallons",
    current_stock_level: 1.5,
    max_stock_level: 2,
    daily_burn_rate: 0.25,
    last_restock_date: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: "2",
    name: "Sourdough Bread",
    category: "Grains",
    unit_type: "units",
    current_stock_level: 2,
    max_stock_level: 3,
    daily_burn_rate: 0.5,
    last_restock_date: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: "3",
    name: "Free-Range Eggs",
    category: "Protein",
    unit_type: "units",
    current_stock_level: 12,
    max_stock_level: 18,
    daily_burn_rate: 2,
    last_restock_date: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: "4",
    name: "Avocados",
    category: "Produce",
    unit_type: "units",
    current_stock_level: 4,
    max_stock_level: 6,
    daily_burn_rate: 1,
    last_restock_date: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: "5",
    name: "Greek Yogurt",
    category: "Dairy",
    unit_type: "oz",
    current_stock_level: 32,
    max_stock_level: 32,
    daily_burn_rate: 6,
    last_restock_date: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: "6",
    name: "Chicken Breast",
    category: "Protein",
    unit_type: "lbs",
    current_stock_level: 3,
    max_stock_level: 5,
    daily_burn_rate: 0.75,
    last_restock_date: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: "7",
    name: "Jasmine Rice",
    category: "Grains",
    unit_type: "lbs",
    current_stock_level: 5,
    max_stock_level: 10,
    daily_burn_rate: 0.3,
    last_restock_date: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
  {
    id: "8",
    name: "Sparkling Water",
    category: "Beverages",
    unit_type: "cans",
    current_stock_level: 18,
    max_stock_level: 24,
    daily_burn_rate: 3,
    last_restock_date: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: "9",
    name: "Baby Spinach",
    category: "Produce",
    unit_type: "oz",
    current_stock_level: 10,
    max_stock_level: 16,
    daily_burn_rate: 2.5,
    last_restock_date: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: "10",
    name: "Almond Butter",
    category: "Condiments",
    unit_type: "oz",
    current_stock_level: 16,
    max_stock_level: 16,
    daily_burn_rate: 0.5,
    last_restock_date: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: "11",
    name: "Frozen Blueberries",
    category: "Frozen",
    unit_type: "bags",
    current_stock_level: 2,
    max_stock_level: 3,
    daily_burn_rate: 0.4,
    last_restock_date: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: "12",
    name: "Tortilla Chips",
    category: "Snacks",
    unit_type: "bags",
    current_stock_level: 1,
    max_stock_level: 2,
    daily_burn_rate: 0.3,
    last_restock_date: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
];
